# -*- coding: utf-8 -*-
"""List

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KoMRB8-jvmC79cqzO4DmUlYzH9-vARFU

Membuat sebuah program barang dengan ketentuan berikut :
1. Gunakan list untuk menampung barang yang diinputkan
2. Program dapat menambahkan barang
3. Program dapat menghapus barang
4. Program dapat mengedit barang
5. Program dapat menampilkan semua barang
6. program dapat mengetahui apakah barang sudah ada dalam list atau belum
7. program dapat menampilkan index barang tertentu
"""

barang = []

while True :
  print("""pilih salah satu perintah berikut :
  1. menambahkan
  2. menghapus
  3. mengedit
  4. menampilkan
  5. mencari barang
  6. mencari index""")
  perintah = input("masukkan salah satu perintah diatas : ")

  if perintah == '1':
    tambah = input("masukkan barang : ")
    barang.append(tambah)
  elif perintah == '2':
    hapus = int(input("masukkan index yang akan dihapus : "))
    del barang[hapus]
  elif perintah == '3':
    ubah = int(input("masukkan index yang akan diubah : "))
    barang[ubah] = input("masukkan barang baru : ")
  elif perintah == '4':
    print(barang)
  elif perintah == '5':
    cari = input("masukkan barang yang dicari : ")
    if cari in barang :
      print("barang ditemukan")
    else :
      print("barang tidak ditemukan")
  elif perintah == '6':
    carii = input("masukkan barang yang dicari indexnya : ")
    if carii in barang :
      print(barang.index(carii))
    else :
      print("index pada barang tidak ditemukan")
  else :
    break 

print("looping selesai, selamat bekerja")