# -*- coding: utf-8 -*-
"""Stack and Queue

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10sIn6__cmiMRUY8qmyl5SfKFj3GvlfT5

**STACK**
"""

stack = []
size_max = int(input("Masukkan Ukuran Maksimal Stack: "))

def isFull():
	if len(stack) == size_max:
		print("Stack Penuh.")
		return True
	return False
		
def pop():
  if isEmpty() == False :
    print (stack.pop(), "terhapus")

def push():
	if isFull() == False :
		tambah = input("Masukkan Item Baru: ")
		stack.append(tambah)
		print(tambah, "ditambahkan.")
		
def peek():
  top = len(stack) - 1
  if top < 0:
    print("tidak terdefenisi")
  else :
    print("elemen topnya : ", stack[top])

def isEmpty():
	if len(stack) == 0:
		print("Stack Kosong.")
		return True
	return False

def tampilkan(stack):
  print(stack)

pilih = 0
while pilih != '7':
    print('''pilih perintah berikut :
    1. Push = Menambah Item
    2. Pop = Menghapus Item
    3. Peek = Melihat Item Teratas/terakhir
    4. Empty = Memeriksa Apakah Stack Penuh
    5. Size = Melihat Ukuran Stack
    6. menampilkan data''')
    pilih = input("Ketik 7 untuk berhenti \n Masukkan Perintah: ")
    print()
    
    if pilih == '1':
    	push()
    elif pilih == '2':
    	pop()
    elif pilih == '3':
    	peek()
    elif pilih == '4':
    	if isEmpty() == False:
    		print("Stack memiliki isi.")
    elif pilih == '5':
    	print("Ukuran stack saat ini: ", len(stack), "\nUkuran maksimal stack: ", size_max)
    elif pilih == '6':
      print(stack)

"""**QUEUE**"""

antrian = []
size_max = int(input("Masukkan Ukuran Maksimal antrian: "))

def isFull():
	if len(antrian) == size_max:
		print("antrian Penuh.")
		return True
	return False

def isEmpty():
	if len(antrian) == 0:
		print("antrian Kosong.")
		return True
	return False

def dequeue():
  if isEmpty() == False :
    print (antrian.pop(0), "terhapus")

def enqueue():
	if isFull() == False :
		tambah = input("Masukkan Item Baru: ")
		antrian.append(tambah)
		print(tambah, "ditambahkan.")

def size ():
  return len(antrian)

def tampilkan(antrian):
  print(antrian)

pilih = 0
while pilih != '6':
    print('''pilih perintah berikut :
    1. Enqueue = Menambah Item
    2. dequeue = Menghapus Item
    3. Size = Melihat Ukuran Queue
    4. Empty = Memeriksa Apakah Stack Penuh
    5. menampilkan data''')
    pilih = input("Ketik 6 untuk berhenti \n Masukkan Perintah: ")
    print()
    
    if pilih == '1':
    	enqueue()
    elif pilih == '2':
      dequeue ()
    elif pilih == '3':
    	print("Ukuran queue saat ini: ", len(antrian), "\nUkuran maksimal stack: ", size_max)
    elif pilih == '4':
      if isEmpty() == False:
        print("antrian memiliki isi.")
    elif pilih == '5':
      print(antrian)